---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
     - id: check-yaml
       args: ['--allow-multiple-documents']
     - id: check-json
     - id: detect-aws-credentials
     - id: detect-private-key
     - id: trailing-whitespace
     - id: check-added-large-files
       args: ['--maxkb=150']
     - id: check-byte-order-marker
     - id: check-merge-conflict
     - id: check-symlinks
     - id: end-of-file-fixer
     - id: no-commit-to-branch
       args: [--branch, master]
     - id: pretty-format-json
       args: ['--autofix']
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: 'v2.2.2'  # Use the sha / tag you want to point at
    hooks:
      - id: pylint
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    sha: 1.10.3
    hooks:
      - id: forbid-binary
      - id: shellcheck
  - repo: git://github.com/dnephin/pre-commit-golang
    sha: HEAD
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: go-lint
      - id: go-unit-tests
  - repo: git://github.com/kintoandar/pre-commit.git
    sha: v2.1.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
