add_newline = false
format = """\
    $shlvl\
    $directory\
    $python\
    $golang\
    $ruby\
    $rust\
    ${custom.fairwinds}\
    $aws\
    $gcloud \
    $helm\
    $kubernetes\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $line_break\
    $jobs\
    $cmd_duration\
    $character"""

[shlvl]
disabled = true
format = '[\($shlvl\)]($style)'
symbol = "↕️ "
style = "green"
threshold = 2

[character]
error_symbol = "[✗](bold bright-red)"
success_symbol = "[▶](bold green)"
use_symbol_for_status = true

[directory]
style = "green"
truncation_length = 8
[directory.substitutions]
"~" = "home"

[aws]
disabled = true
style = "dimmed yellow"
displayed_items = "all"
symbol = "  "
format = "[$symbol$profile(\\($region\\))]($style) "

[gcloud]
disabled = true
symbol = " "

[kubernetes]
symbol = "⎈ "
format = "[$symbol$context( \\($namespace\\))]($style) "
prefix = " "
style = "bright-blue"
disabled = false

[custom.fairwinds]
symbol = "🚀"
command = "echo $PROJECT|$INVENTORY"
when = """ test "$INVENTORY" != "" """
prefix = " "
style = "bold red"

[jobs]
disabled = false
symbol = "&"
style = "yellow"

[git_branch]
disabled = false
format = "[$symbol$branch]($style) "
symbol = " "

[git_status]
disabled = false
modified = "±"
style = "yellow"

[golang]
symbol = " "
style = "bright-cyan"
format = "[$symbol$version]($style) "

[python]
symbol = " "
format = "[${symbol}${version}( \\($virtualenv\\))]($style) "

[cmd_duration]
min_time = 3000
format = "[$duration]($style) "

[line_break]
disabled = false

[rust]
format = "[$symbol$version]($style) "
symbol = " "

[helm]
disabled = true
format = "[⎈ $version](bold white) "
