# Don't print a new line at the start of the prompt
add_newline = true
# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10
prompt_order = [
    "directory",
    "python",
    "golang",
    "ruby",
    "rust",
    "custom.fairwinds",
    "kubernetes",
    "aws",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "custom.weather",
    "line_break",
    "jobs",
    "cmd_duration",
    "character",
]

# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are configuring is "character"
error_symbol = "$? ▶"
symbol = "▶"
style = "green"
style_failure = "bold bright-red"
use_symbol_for_status = true

[directory]
style = "green"
truncation_length = 8
[directory.substitutions]
"~" = "home"

[aws]
disabled = true
style = "dimmed yellow"
displayed_items = "all"
symbol = "  "
[aws.region_aliases]
ap-southeast-2 = "au"
us-east-1 = "use1"
us-east-2 = "use2"

[kubernetes]
symbol = "⚓"
prefix = " "
style = "bright-blue"
disabled = false

[custom.fairwinds]
symbol = "🚀 "
command = "echo $PROJECT:$INVENTORY"
when = """ test "$INVENTORY" != "" """
prefix = " "
style = "bold red"

[jobs]
symbol = "& "
style = "yellow"

[git_branch]
symbol = " "

[git_status]
modified = "±"
style = "yellow"

[golang]
symbol = " "

[python]
symbol = " "

[cmd_duration]
min_time = 3000

[custom.weather]
command = 'curl wttr.in/80814?format="%t%20%w\n"'
disabled = true
when = """ true """
style = "white"
prefix = ""
