# Don't print a new line at the start of the prompt
add_newline = false
# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10
prompt_order = [
    "directory",
    "python",
    "golang",
    "ruby",
    "rust",
    "custom.fairwinds",
    "kubernetes",
    "aws",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "line_break",
    "jobs",
    "cmd_duration",
    "character",
]

# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are configuring is "character"
use_symbol_for_status = true

[directory]
style = "green"
truncation_length = 8
[directory.substitutions]
"~" = "home"


[aws]
disabled = true
style = "dimmed yellow"
displayed_items = "all"
symbol = "  "
[aws.region_aliases]
ap-southeast-2 = "au"
us-east-1 = "use1"
us-east-2 = "use2"

[kubernetes]
symbol = "⚓"
prefix = " "
style = "bright-blue"
disabled = false

[custom.fairwinds]
symbol = "🚀 "
command = "echo $PROJECT:$INVENTORY"
when = """ test "$INVENTORY" != "" """
prefix = " "
style = "bold red"

[jobs]
symbol = "& "
style = "yellow"

[git_branch]
symbol = " "

[git_status]
modified = "±"

[golang]
symbol = " "

[python]
symbol = " "
